### ISSUE TITLE
Annotating Time Series

### ISSUE THREAD

**Issue by bastibl** [gnuradio/SigMF#10]
I think it's quite common to record some kind of time series data together with the actual signal.
For example, I usually record GPS traces. Someone else might record other kinds of sensor data or just log interesting events in a notebook (if someone walked through the experiment, for example).

Intuitively, I would think that this are annotations (also because annotations support latitude and longitude), but the current specification requires to annotate based on samples. The problem is that the data is usually recorded independent from the sample stream and doesn't directly map to a sample index. To me, it feels wrong to do a lot of preprocessing (map time to sample index) to get my raw data into the SigMF format. Apart from that, there might not even be samples recorded at a given point in time (due to gaps between segments). Also, if the segments get large, clock drift might be become a problem.

AFAIS, the only option would be to add the time series as a custom object to global. Like

```
{
    "global": {
        "bastibl:gps": [
            {time1, reading1},
            {time2, reading2}
         ]
    }
}
```

I think it would be nicer to also allow annotations based on time stamps. Currently, annotations seem to be really tuned towards signal identification, i.e. labeling some samples.

**Comment by smunaut** [comment]
I wouldn't allow that in the core spec.  To do anything with those _someone_ will have to map the sample index to timestamp and I'd rather it'd be the recording application rather than force the burden on all the reader, unless you allow all the readers to just ignore those by putting it in an extension.

**Comment by bastibl** [comment]
I don't get why everything has to be mapped to a sample. If you have temperature recording, a picture that is taken at some moment, or a GPS traces, then, for the above mentioned reasons (independent recording, no data available, clock drift), it doesn't make a lot of sense to map it to a sample. Still, I would regard it as an "annotation".

**Comment by smunaut** [comment]
I said "sample index" not sample. It's just a different time unit that's much simpler (i.e. single monotonic integer). There might be no actual sample data for that index.

Logically those infos will need to be displayed or interpreted in relation to the actual data which means they'll need to be time synced. If you're not going to map those annotation to the actual signal recorded, you might as well not put them in the file.

**Comment by bastibl** [comment]
With segments recorded at different sample rates, I don't see how this is a much simpler notation for time. 
Looks like I don't understand the definition of sample index. I thought it is the index of the sample in the file (plus optional offset). But it seems to be an abstract concept for time. Also I wouldn't know how to properly assign a "sample index" to data that is recorded in a gap between segments with different sample rates.
That's too complicated. I'll just use the private namespace.

**Comment by bhilburn** [comment]
Re-opening this because I think it's an important concept, and perhaps something needs to be clarified in the spec.

So, @bastibl, perhaps I can provide some background to why we made the original decision. Going back to your example of "someone walked through the experiment", I generally agree, you would want to attach that annotation to some place in `time` so that when you are visualizing the dataset, for example, at some point you see an annotation in the waterfall (or whatever) that says "someone walked through it". 

The issue, though, is that the dataset is a file of stored samples. So, in order for the visualization tool to know where to display that annotation (if it was attached to a time unit), it would need to understand how sample indices mapped to time (via sample rate), and then show it appropriately. So, instead of requiring that, we thought it would be easier to simply attach it to `sample_index` instead.

Given that background, is there something about this system that you think is deficient, awkward, or that won't do what you need it to? I want to be certain that if it isn't going to do something, we are aware of it and consciously decided to proceed, anyway.

**Comment by bastibl** [comment]
I think I still don't understand your concept of a "sample index". 

> I said "sample index" not sample. It's just a different time unit that's much simpler (i.e. single monotonic integer). There might be no actual sample data for that index.

So if I have a recording with one sample per second and at t=0 starts a segment with 2 samples. Then there is a 2 second gap and the next segment starts at t=4s. So the first sample in the second segment is the 3rd sample in the file, but has sample index 4, since there are 2 virtual samples in the gap. This are points in time where "There might be no actual sample data for that index."

Based on your above description, this is how I understand the "sample index", but I can hardly believe that it is intended to be like that, since calculation of this index will get very confusing when there are many segments with varying sample rates.

Also, then the sample index doesn't tell anything about where the sample is stored in the file...

**Comment by bhilburn** [comment]
There is no way to specify a jump in sample indices in the dataset, so the scenario you just described isn't possible. The `sample_index` is monotonic from `0+offset` to `n-1`.

At this point, I'm rather confused, to be honest, so it may be good to have @smunaut clarify.

**Comment by smunaut** [comment]
I was thinking of multiple files using "offset" and not the so called capture segments.

TBH the case of multiple sample rate I just don't think should be allowed. sampe_rate is a fundamental property of how to interpret the data and shouldn't be changed in the middle of a stream (like data type for instance).

**Comment by bastibl** [comment]
So, I think, my initial understanding of sample offset was correct.

> So, in order for the visualization tool to know where to display that annotation (if it was attached to a time unit), it would need to understand how sample indices mapped to time (via sample rate), and then show it appropriately. So, instead of requiring that, we thought it would be easier to simply attach it to sample_index instead.

I don't know how a tool could work without a notion of time. Even in the simplest case, when a visualization tool plots a line graph with two segments. It has to relate the width of the gap between the segments to the duration of the segment. Can this work without converting to time?

**Comment by smunaut** [comment]
It could just not display the gap at all and just display like a red vertical line and not care about how long that gap of time is at all.

**Comment by bastibl** [comment]
yes, if there is only one application that is recording. In practice, the data might be recorded from several independent sources. Like `uhd_rx_cfile`, `gpsd`,  guy with notebook in his hand, and maybe many others.

**Comment by smunaut** [comment]
Well even in that case, the burden of converting from time to sample index should be on the writer which is trying to do something special rather than force every reader app to support it.

**Comment by bastibl** [comment]
I just thought it would be nice to, for example, open a SigMF file in Inspectrum and being able to select a time series recording as a new plot (with proper spacing between segments and data even in the gaps).

I cannot understand why one would be willing to drop support for (in my opinion) such essential functionality in favor of saving one line of code.

`t = t_segment_start + (sample_index - sample_index_segment_start) / sample_rate`

Also segments with different sample rates (as currently specified) could hardly work with this. It would require to resample all segments to a common sample rate to go for the "sample index"-approach.

I give up...

**Comment by smunaut** [comment]
My understanding of @bastibl proposal was that instead of only having "sample_start" to specify where annotation start, you'd have something like "time_start" as an alternative.

But then every reader application has to support both (since any annotation could use either and be compliant). That IMHO is a too high burden to place on anyone that has to read the file.

The same burden could be put on the writer application, and since it's the one actually wanting to store those data, that would be the right place to put that burden.

**Comment by bhilburn** [comment]
@bastibl - Any comments or feedback on my questions or @smunaut's comments?

**Comment by bhilburn** [comment]
Okay, I'm going to close this one out for now, as it seems there are no further arguments for creating time-series annotations. If anyone wants to discuss this further, please re-open!
