### ISSUE TITLE
Allow for SigMF files to describe non-SigMF data files

### ISSUE THREAD

**Issue by jsallay** [gnuradio/SigMF#163]
I think that the SigMF format is presently narrowly focused on data files where the user has control over the recording, but there are cases where that isn't possible or convenient.  I may have an application that requires data to be in a different format, but I would still like to use SigMF to describe the data in it.  Why would I do this?  Because SigMF provides a consistent, human-readable description of the metadata associated with a file.  It can be useful for more than just data processing.  In the above example, I may want to look at or analyze the metadata independent of the contents of the data file.  Or I may come back to the file in several years having forgotten about its purpose.

In this way SigMF would become a universal file descriptor.

As a concrete example, say that I am working on code that processes VITA49 streams which have signal metadata and data interleaved.  I may want to save off some test data files and metadata about them in a human readable format.  Metadata like sample rate and center freq apply to this data file even though the data isn't contiguous IQ samples.  It is still useful to open up a file and see the metadata about the stream.

In order to provide this functionality, I think there are three important pieces.
- [ ] SigMF metadata files need to be able to specify the file name that they describe.  I think this is generally a useful thing, but is required here.
- [ ] There needs to be a way to specify in a metadata file, that the described data is not a compliant data file.  We wouldn't want a user to attempt to process my VITA49 stream file assuming that the data is continuous in time.  It is better to complain immediately that the data can't be handled.
- [ ] There needs to be agreement that making SigMF a universal file descriptor is a good goal for the project.

**Comment by bhilburn** [comment]
Going through the three items in the list:

- The first is covered in #170 and I think we are all in agreement that is a good idea 👍
- I strongly agree with the second point, and any implementation here would have to protect the meaning of a "Compliant" for both data and applications.
- Discussion definitely comes down to the third item.

I might even rephrase the last question to be, "Should we provide a way to indicate that Metadata points to a non-SigMF Dataset and still call that Metadata (and the Metadata alone) as Compliant."

Thinking through this, the point is kind of interesting because I both (a) don't think this is a problem that SigMF should care about solving, and (b) if we don't provide a common way to do it everyone will do it anyway.

More detail, in terms of actual implementation:

We are already providing for Metadata to point to specific Dataset files (#170) and thus dropping the filename extension hard requirement (will move to a RECOMMENDED). This already opens the door to other filetypes. If we do NOT specifically allow for this, there is already a super clear path for any user that cares about this to implement it on their own: create an extension that makes some new field, `extension:dataset_type`, with some list of allowed types of non-SigMF datasets. That solves the problem super easily and simply.

So then, which of these three paths is best for SigMF:

- We say 👆👆👆 is the answer, and that any user that cares can do it themselves (could work because no Compliant apps have to even think about it).
- We say a lot of people care about this, but it's not Core, so we make a canonical extension so everyone does it in a consistent way (could work because Applications will know non-SigMF support is needed when they parse the core:extensions list and can punch out).
- We make it an optional field in Core (could work because Apps, when they see a non-SigMF datatype, can punch-out, and we make a rule that says Compliant Apps don't have to care).

Thoughts, @jacobagilbert, @Teque5? Also tagging @sammp because she mentioned she cared about this.

**Comment by bhilburn** [comment]
Talked about this and related topics with @amymalady for a while last night, and Amy raised some really great points that tie to both this issue and #170.

The short of it is that one of the major values of SigMF is the ability to easily mmap data into memory with easily understandable metadata that describes it. Right now, we force users to create one-off extensions to bring that benefit to other filetypes. This comment ([here](https://github.com/gnuradio/SigMF/issues/170#issuecomment-929523064)) from @jacobagilbert, for example, is exactly that: it provides the fields necessary to understand how to mmap data out of a BLUE file in the same way you would with a SigMF Dataset so that you can still benefit from all the other great stuff SigMF gives you. @jsallay raised this at GRCon when he asked for a way to "describe the structure of other datasets".

This feature is dependent on the issue described in this thread, but goes a step further. Laying it out:

- This issue is specifically about a way to indicate that a dataset file is **not** a SigMF file, and specify a different type, and still call the Metadata valid.
- One step beyond that would then be providing a canonical way to point to the sample data in that file so that you could mmap it as you would any SigMF recording.

Pulling on the second bullet a bit, per that comment in the link above, DeepSig is doing this with two fields, `data_size` and `data_offset`. This is a super simple solution, and maps arbitrarily to formats with data payloads. @amymalady also noted that this really isn't a new burden on Readers - in fact, they are just the two arguments you would pass to mmap, anyway.

Taking it one step even further - the design of our Captures array actually allows us to do this even over interleaved metadata and data packets streamed to disk (e.g., a VITA49 capture).

Anyway, would love to hear other thoughts, here, too.

**Comment by jacobagilbert** [comment]
This (mmap data files) is precisely why we do this at DeepSig. Effectively we treat the presence of these fields as an indication that the data file is not standard SigMF (and imply 0 and file_size if the data is 'real SigMF').

If they are already 0 and file_size, well... the data *is* SigMF (provided the proper file name convention).

**Comment by jsallay** [comment]
I like this direction. Could you walk me through how you would expect
vita49 to work? Are you thinking that each days packet would be it's own
capture?

I think vita49 is the most complicated case that I have in mind, so If we
have an adequate solution for it, then I think I'll be good.
