### ISSUE TITLE
Extensions support

### ISSUE THREAD

**Issue by smunaut** [gnuradio/SigMF#2]
I would suggest that the spec specifies the process for extensions.

A few thought about this :
* Extensions should have their own namespace  and be listed in the official spec with a reference to their own spec. Their own spec should follow the same format and also provide a valid schema .json .
* The ```global``` section should hold a list of extensions used in  a given SigMF file. And for each extension a 'requirement level'. This would either be : 
  * ```informational``` meaning the extensions provides just additional information but those fields can be safely ignored.
  * ```required``` which would mean that understanding that extension is required to understand the node where it's used and application should ignore the entire node where such an extension is used because that extension changes the way to interpret that node.

```json
{
  "global": {
    "core:extensions" : {
      "gr": "informational",
      "xxx": "required", 
    }
  }
}
```

**Comment by bhilburn** [comment]
I think extensiblity is an important part of making sure SigMF isn't ephemeral on a time scale, and can grow & change as needed with new applications in the future.

I like @smunaut's suggestion a lot. For me, the only question is do we want to use the value `informational` instead of `optional`?

**Comment by bhilburn** [comment]
As discussed in #3, we also need to explicitly define what it means to be compliant without extensions. @osh's suggestion, for example, was "Portable SigMF Compliant". Moving this discussion, here, as #3 was resolved.

**Comment by mbr0wn** [comment]
Agree with `optional`. More common language.

**Comment by bhilburn** [comment]
Working on the "extensions" [branch](https://github.com/gnuradio/SigMF/tree/extensions)

Questions that have come up:
1. We are requiring that users specify the extensions that are `required` and `optional`. Really, what we care about, is them specifying the `namespace`. What if multiple extensions provide the same namespace string? Should we try to address namespace collisions?
2. Is it worth merging extensions that meet certain standards into the SigMF repository so that they become canonical? This would help address problem #1, too.
3. If extensions are to be allowed to create new datatypes, then I think we ought to namespace datatypes (the datatypes in the main spec would be part of `core`). Thoughts?

TODO:
* We need to provide template Extension[.md]  and schema files.

**Comment by bhilburn** [comment]
Thoughts from anyone on my questions, above?

**Comment by kpreid** [comment]
On 1: #20 is my proposal to formalize namespace collisions, by reusing the existing work in XML Namespaces.

On 3: Datatypes do not need to be formalized because they do not appear in SigMF recordings; they are a matter of specification text only.

**Comment by bhilburn** [comment]
Okay, so, here's my plan for my list above:

1) Work will happen in #20.
2) Yes, I plan to do this unless I hear a convincing argument otherwise.
3) The spec will do this anyway.

Template extension files: This will happen in #13.

Feel free to re-open this if anyone would like to discuss the above items!
