### ISSUE TITLE
Require that segments can be safely split

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#23]
Context: An application might have limitations on what kind of changes between segments it can handle and how well. For example, it might not be able to handle a sample rate change at all, or might reinitialize its processing for each segment, losing something along the way. A sufficiently simple-in-the-mind-of-the-author application might get the bright idea to require that its input have exactly one segment.

I propose that this be prohibited. In particular, a compliant application MUST **treat consecutive segments whose metadata is all equal for the purposes of that application** (that is, it may be different in values that are ignored by the application such as unknown extensions) **in the same way as it would a single segment.**

This also implies a constraint on segment metadata in general, relevant to the design of extensions: that it should in general apply to “all the samples in this segment” and not in some way “the span from the beginning to the end of the segment”. To borrow a term from physics, __all segment metadata should be [intensive properties](https://en.wikipedia.org/wiki/Intensive_and_extensive_properties).__

Metadata where this constraint is problematic can instead be represented as annotations.

A nice property that results: taking an existing SigMF data set and adding some segment metadata which applies to ranges of samples that were not previously the boundaries of segments, therefore splitting segments, cannot change the meaning of the existing metadata.

**Comment by kpreid** [comment]
Independent suggestion, but makes sense done together with the above: require that capture segments have nonzero length (that is, no two capture segments have the same `sample_start`).

**Comment by mbr0wn** [comment]
This is, IIRC, what we had in mind at the hackfest, but I like making this explicit.

**Comment by bastibl** [comment]
I'm not sure how this can work in practice. If the number of samples in a segment and its duration (know from the time stamp) is slightly off, one cannot know if this is because:
- clock drift (the segment was split as described above and should (ideally) be treated as a single segment)
- someone deleted samples on purpose, creating a gap between segments
- there were overruns and the SDR restarted (possibly leading to a strong transient during the first samples of the following segment)

I don't get, how one can differentiate between the cases. And why force people to treat these cases the same.

**Comment by kpreid** [comment]
@bastibl It seems to me that those cases are ambiguous whether or not additional sample splitting is allowed (for example, changing frequency implies a new segment but does not imply any one of the above glitches).

Perhaps there should be a notion of a “sample clock” so that gaps and such can be represented independently of “real” time?

**Comment by smunaut** [comment]
The "segments" is a pretty bad name. When discussed live at the hackfest, the goal was never to have disjoint piece of data (you'd use several files for that). (that's my understanding at least).

They were just written that way because the parameters / infos / metadata written in them are valid until the next segment 'sample_start', rather than have a fixed sample length. Basically to store things like frequency  changes or gain changes or things like that in a continuous capture.

But this whole "segment" naming confuses things more than anything IMHO.

**Comment by bhilburn** [comment]
I've moved discussion of the `segment` name over to #35.

Okay, so my understanding of @bastibl's argument is that if there is a gap in data pointed to by two different `capture` segments, then mandating an application treat them as one continuous block of samples is problematic because there is a hole in the middle. 

My understanding is actually different from @smunaut's, I think, because I was thinking of the current SigMF spec as allowing for those gaps rather than requiring separate files. If an underrun occurs, for example, that would create a gap, but I don't think you would want an entire new SigMF recording. (Am I understanding your comment correctly, here?)

What about this re-wording of @kpreid's suggestion:
When consecutive `capture` segments whose metadata is equivalent for purposes of that application (i.e., it may be different in values ignored by the application such as optional values or unknown extensions) and whose portions of the datafile are continuous (i.e., there is no gap in samples), a compliant application MUST treat the consecutive segments as it would a single segment.

**Comment by kpreid** [comment]
In order to make that statement we would need to define "whose portions of the datafile are continuous" in terms of concepts from the SigMF specification. Which is a problem, because as things stand there is no way to differentiate any of these cases:

1. recording with a known underrun glitch or pause in recording
2. continuous recording where the RF sample clock is significantly wrong vs. nominal sample rate
3. continuous recording where the wall-time clock is significantly wrong, or where it was not sampled accurately vs. the RF sample clock

For example, one way to disambiguate would be to define a field for ending wall-time as well as a starting wall-time. If this is identical to the next segment's start time, then there is no gap (and so any inconsistency between sample index, wall time, and sample rate must be either case (2) or case (3)); if it is not identical then there must be a known gap (case (1)).

I think it makes sense to allow gaps (for example, to have an efficient recording of many bursts).

**Comment by bhilburn** [comment]
Okay, please review & comment on #47!

**Comment by bhilburn** [comment]
Closed by merge of #47.
