### ISSUE TITLE
License Considerations for Python Module

### ISSUE THREAD

**Issue by jacobagilbert** [gnuradio/SigMF#254]
Currently this repository (housing the specification AND the example python module) is licensed under Attribution-ShareAlike (CC BY-SA 4.0) however even the originator of this license [discourages its use for code](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).

I believe the specification being CC licensed makes sense, however we should probably consider a GPL variant for the python module. Given this is simply a reference implementation to access an open source specification, I don't think there are any real concerns with this code being used commercially... however we may want some copyleft guarantees.

**Comment by jacobagilbert** [comment]
@Teque5 @777arc @willcode @mormj - your inputs here are also appreciated.

**Comment by bhilburn** [comment]
Summarizing my thoughts:

- The CC license is exactly the right thing for the specification, but when I selected it originally, I hadn't planned on merging code into this repo, and after we did that, it just didn't occur to me to re-assess.
- I very much agree, the CC license is not appropriate for the Python code.
- I'm generally against maintaining two separate licenses in a single repo. Is it possible? Yes. Can be it confusing and painful? Also yes.
- I think splitting the code out into it's own repo is still the best remedy for our issues with the spec / code intermingling (likewise with the spec releases getting held-up by the code not being up-to-date). I know @Teque5 was not a fan of that, though.
- @jacobagilbert suggested submoduling the code, which I think is a reasonable compromise.
- In terms of the license for the code, I would say GPLv3, which enforces both the Attribution and ShareAlike clauses we currently have on the CC license.

**Comment by gmabey** [comment]
One reason this came up was because I was trying to select an appropriate license for a new piece of software.  In the spirit of making the lawyer step easier, I said to myself, if I select a license that is identical to other stuff that is related, then that's one less piece of legalese that will have to be reviewed by lawyer types -- *in any organization* (not just my own).

That's why I first considered selecting CC for my software, and then determined that it was in appropriate.

Anyway, that same rationale could be used to select a license for the python code -- if it's *identical* to whatever python or numpy is using, then it's just less to deal with at legal review time, for *everyone* (well, for all commercial enterprises that want to consider using it).

**Comment by willcode** [comment]
If the code is a reference implementation, and we want non-GPL code to adopt SigMF, then I would think a more permissive license would be useful.

**Comment by gmabey** [comment]
@bhilburn wrote:
> @jacobagilbert suggested submoduling the code, which I think is a reasonable compromise.

At first I agreed, that a submodule would be a nice compromise -- but then I thought, "Which is the sub?"

Assuming that the python code changes more often than the spec (which I think is a good assumption) then if the python-repo were the submodule, then the spec-repo would need new commits in order to reference the latest python.

If the spec-repo were to be the submodule, then it feels like the spec isn't the General Contractor around here, but instead just a sub.  Maybe there's nothing to that feeling and it should be disregarded though.

I have mentioned before that I hope to someday contribute a MIDAS-to-SigMF converter.  One complication I found was that the `bluefile.py` I got from another github repo is LGPL. My plan was to include (in that same `tools/` directory) a `LICENSE_bluefile.py.txt` with the intent to redistribute that file under *that* file under *that* license -- but I really don't know what I'm doing in this domain.

Regardless, the possibility exists (I hope) of covering different parts of a single repo with different licenses.

**Comment by jacobagilbert** [comment]
The python module would be a submodule in the SigMF repo. Releases to the SigMF spec would update to point to the latest python module release.

It's not perfect but would be pretty functional. They don't need to (and are not now) in perfect lock step anyway.

**Comment by Teque5** [comment]
If we split the repos, I don't think the code has to be a submodule. I almost think the repo with JUST the spec and the example corresponding SigMF logo file is the best way forward. The python implementation should just referenced as a good implementation of the spec. This can be expanded to other good implementations in GNU Radio, Rust, whatever.  Within the python module we will clearly state it corresponds with the spec version X.Y.Z.

@gmabey We spent some time recently building a modern Bluefile <-> SigMF converter, but I wouldn't say it is of the **highest quality** yet. If it starts covering most use cases I will start the process for public release from my org. Might be a topic for a separate issue.

As for the license, we (my org) have decided LGPL is the best way to get code into the wild while keeping the cartoon Richard Stallman on our shoulder happy.

**Comment by jacobagilbert** [comment]
To summarize the latest developments with this as of December 2022:

1. There seems to be a strong consensus that we split the python module out of the specification repository (or vice versa). If we intend to keep the same python package name (e.g.: `sigmf`) It might make sense to keep the python module here and create `gnuradio/sigmf-spec.git` though I don't feel strongly about this
1. The spec will remain under the current CC license
1. LGPLv3 is the leading license choice for the sigmf package, but this requires some additional consensus from the SigMF stakeholders.
1. Issues will be tracked separately for code and spec (another benefit!)
1. To submodule or not... pip should be the primary place folks get the python sigmf module from, so submoduling is probably not necessary. Looking for input here also though.

**Comment by Teque5** [comment]
> To summarize the latest developments with this as of December 2022:
> 
> 1. There seems to be a strong consensus that we split the python module out of the specification repository (or vice versa). If we intend to keep the same python package name (e.g.: `sigmf`) It might make sense to keep the python module here and create `gnuradio/sigmf-spec.git` though I don't feel strongly about this
> 2. The spec will remain under the current CC license
> 3. LGPLv3 is the leading license choice for the sigmf package, but this requires some additional consensus from the SigMF stakeholders.
> 4. Issues will be tracked separately for code and spec (another benefit!)
> 5. To submodule or not... pip should be the primary place folks get the python sigmf module from, so submoduling is probably not necessary. Looking for input here also though.

1. Between these options I think having the spec called `sigmf` makes more sense. Maybe **ii**? In that case we can "move" the repo and it should preserve history, wiki, et cetera.
    i. `sigmf` and `sigmf-spec`
    ii. `sigmf` and `sigmfpy`
    iii. `sigmf` and `pysigmf`
    iv. `sigmf` `sigmf-python`
2. k
3. k
4. k
5. I always find submoding a pain & confusing for new users so let's not.

**Comment by 777arc** [comment]
I can't imagine a ton of people will be cloning the spec repo, so doesn't make much difference if we submodule or not

**Comment by jacobagilbert** [comment]
Regarding submodule, I lean in this direction of _not_ including it in the spec repo as well. 

Of those choices @Teque5 either `sigmf-spec` and `sigmf`, or `SigMF` and `pysigmf` seems to make the most sense to me. I lean toward keeping the spec repo as-is.

We can definitely preserve git history with a new repository, its the issues and stuff that will need to change for the python module.

**Comment by bhilburn** [comment]
LGPL for the code is good by me.

Also, I think the spec repo (this one) should remain unchanged in name.

**Comment by jacobagilbert** [comment]
I agree keeping this (spec) repository name as a preference. 

How do we feel about changing the name of the python module to `pysigmf`?

**Comment by 777arc** [comment]
pysigmf definitely clears up any ambiguity

**Comment by gmabey** [comment]
is everyone in favor of keeping the python module the same -- like `import sigmf`? I am; I *hate* those pesky two wasted characters for modules like pymongo, pyside, pysword, pyclustering not to mention numpy and scipy LOL.

Actually, I've never used pysword or pyclustering -- I just looked them up har har.

No seriously I don't object to the name numpy but I *do* like `import sigmf` in which case I don't agree that the new repo name be pysigmf, since in my mind that would imply `import pysigmf`.

How about `sigmf-python`?

**Comment by jacobagilbert** [comment]
I do prefer `import sigmf` myself... `sigmf-python` for the new repository name is also reasonable as far as I am concerned. It would be nice not to break pypi.

**Comment by 777arc** [comment]
Yea I would support that too

**Comment by jacobagilbert** [comment]
Done. https://github.com/gnuradio/sigmf-python

I am going to wait for the final merge requests related to the python module to be closed out before I make this move.

**Comment by Teque5** [comment]
> I do prefer `import sigmf` myself... `sigmf-python` for the new repository name is also reasonable as far as I am concerned. It would be nice not to break pypi / pip / everyones everything using `sigmf`.

Regardless of the project name we will still be using `import sigmf` and pushing to that same pypi project.
