### ISSUE TITLE
Bit Widths

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#3]
A comment I received from someone reviewing SigMF:

> I think it would be useful to support sample sizes beyond the current 8/16/32 bits. As an example, I am using a backend that spits out 10 bit real data, and it would be a huge waste of bandwidth/storage capacity to have to expand it to 16.
> 
> This does however also imply that tools would need to support the correct interpretation of such packed formats.

The commenter raises an excellent point. We don't want to exclude the use of SigMF in systems that aren't using a power-of-two sample length (or make it unduly burdensome to use), but at the same time, requiring it would add possibly unneeded complexity to tools.

Perhaps the solution is to add a clause that allows other dataset formats, but not to require them for spec compliance. Thoughts?

**Comment by smunaut** [comment]
Yeah, other packed format should be optional. Otherwise you'll just have a bunch of non-compliant software just because reaching compliance is too annoying.

Format conversion utilities should definitely be part of the "utility pack" that we make available so that if a format is not supported, well you can just convert.

**Comment by jarn0ld** [comment]
> Perhaps the solution is to add a clause that allows other dataset formats, but not to require them for spec compliance. Thoughts?
I would agree as we should not force every tool to be compatible with every possible data format.
One could still think about a tool that converts the data to the closest standard compliant data type and adjusts the metadata accordingly for compatibility with other tools.

**Comment by osh** [comment]
We also don't want people to be able to say "its sigMF compliant" and then hand over a pile of annoying data that forces everyone to implement their one-off oddities to be able to deal with

**Comment by bhilburn** [comment]
Okay, so it sounds like the consensus is that we should make sure that the specification allows the use of other dataset formats, but does not require them to be compliant.

So, then, how do we allow for defining new dataset formats? We could simply add a clause to that section that states something:

```
Other dataset formats may be used and should be described using the same syntax, but supporting them is optional and shall not be required for SigMF compliance.
```

**Comment by osh** [comment]
im not sure 10bit should be allowed to be 'compliant' for posting / sharing with the world.   this is more of an internal use  / custom configuration format IMO.   I certainly wouldn't want someone posting this kind of file up and expecting it to serve as a good reference for anything --

**Comment by bhilburn** [comment]
Hm, we may differ in opinion, here, @osh. I agree with you that pragmatically a dataset formatted with 10bit samples probably won't be that useful to others, but the goal of the specification isn't to guarantee that every dataset in the world is useful, only that they can be understood. If someone wants to post a dataset with 6bit samples, they are free to, but they shouldn't be surprised if nobody cares about it.

Thoughts from everyone else?

**Comment by osh** [comment]
the whole point of a standard is to agree on a relatively sane and well defined way of doing things we can all agree on.   I understand people may want to use a version of that standard in their one-off application - which is fine within an organization -- but once you let 50 people drive a boat through a standard and support totally random optional features which may or may not be implemented in tools using the standard -- you completely obliterate the point of having a standard at all.       Yes it complied with the standard but you didnt implement our optional customizations,  see Vita49 Extended headers, etc etc -- every standard ever that opened this avenue up boundlessly.    Now for metadata its fine to jam extra labels in there, but if you can't even read the data in a simple standard format which everyone will implement, I do NOT want this to be compliant to the point someone can say "oh I posted a nice SigMF compliant dataset of it"  -- which is not true because it breaks everything under the sun.

**Comment by smunaut** [comment]
That's why I'd suggest to define other custom bit width as "required extensions".

**Comment by osh** [comment]
I personally feel that 10bit mode is beyond what should be a required extension.  It is not needed 99% of the time, and creates numerous headaches with libraries and implementation that do not justify it -- IMO this should be an 'optional extension' and not 'compliant'

**Comment by bhilburn** [comment]
I think @smunaut's suggestion, using extensions as defined in #2, is a good one. It allows for folks to use the SigMF standard for whatever bizarre format they want, but is also clearly outside of compliance. That was the goal of my original statement, but @smunaut's solution is more elegant.

So, the proposition then is that we make no mention of other dataset types in the SigMF standard itself, and if people want to use them they can define a full extension using whatever mechanism we agree upon in #2 to do so.

Does everyone agree?

**Comment by bhilburn** [comment]
> I personally feel that 10bit mode is beyond what should be a required extension. It is not needed 99% of the time, and creates numerous headaches with libraries and implementation that do not justify it -- IMO this should be an 'optional extension' and not 'compliant' --- does gnu radio even have a source block for 10 bit right now? the answer is no -

Just to be clear, @osh, the proposal in #2 is not to make extensions required or compliant in any way, but only to provide a mechanism by which people may define them if they want them. We are all in agreement that an extension for 10bit dataformat is not *required* for compliance, as no extensions are *required* for compliance.

**Comment by smunaut** [comment]
@osh  By "required extension" that means the file defines that a software _must_ support that extension to read that file at all and should refuse to load it if it doesn't. Not that the extension is required to be supported to be SigMF compliant.

**Comment by osh** [comment]
I guess my concern is:   Say we have some kind of competition where we ask people to submit datasets.   I want to be able to say, 'you must submit a sigMF compliant' dataset, and not have to deal with weird abnormal extensions to accomplish basic tasks like reading in samples.    in this case the extension *is* required in order to even read a sample.

**Comment by smunaut** [comment]
Well you can define in your rules that the datasets shouldn't make use of any extensions as "required".

**Comment by osh** [comment]
We just need an official name for it -- "Portable SigMF Compliant" or something -- so it can be easily referred to and we dont run into these issues

**Comment by bhilburn** [comment]
Great points, @smunaut and @osh. I think this is more pertinent to #2, so let's carry the conversation on, there.

The conclusion to this thread, then, is that we will not be adding any verbiage to the standard regarding other datatypes.
