### ISSUE TITLE
Use of the `segment` name

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#35]
In the discussion in #23, there was some feedback regarding the use of the word `segment`:

> The "segments" is a pretty bad name. When discussed live at the hackfest, the goal was never to have disjoint piece of data (you'd use several files for that). (that's my understanding at least).
> 
> They were just written that way because the parameters / infos / metadata written in them are valid until the next segment 'sample_start', rather than have a fixed sample length. Basically to store things like frequency changes or gain changes or things like that in a continuous capture.
> 
> But this whole "segment" naming confuses things more than anything IMHO.

So, the way I think of `segments` is that the datafile itself does not exist in the form of segments, *at all*. It is one monolithic data dump. A `segment` is simply a single `JSON Object` in one of the top-level objects that has some metadata that applies to some portion of the datafile.

What are others thoughts on this? Are we using the term in a confusing way? Is it a bad term to have chosen in the first place? Perhaps we can make this better by more clearly defining `segment` in the spec?

**Comment by kpreid** [comment]
It sounds like you're talking about _capture segments_, but you're just saying “segment”. Therefore I point out the terminology is subject to misuse in a different way than you meant to raise!

**Comment by bhilburn** [comment]
So, I think of `segments` as what we now call `Capture Segment Objects` and `Annotation Segment Objects`.

So, for example, this is a capture segment:
```
        {
            "core:sample_start": 100000,    # Mandatory
            "core:sample_rate": 10000000,   # 10 MHz
            "core:frequency": 950000000,    # Now at 950 MHz
        },
```

And this is an annotation segment:
```
        {
            "core:sample_start": 1000000,   # The sample index at which this annotation first applies.
            "core:sample_count": 120000,    # The number of samples that this annotation applies to.
            "core:comment": "Some text comment about stuff happening",
        },
```

The spec definitely uses the word `segment` in what appears to be an ambiguous way, though, as currently written.

**Comment by bhilburn** [comment]
So, after reviewing the use of the word `segment` in the spec, I actually don't see any examples of it being used inconsistently. The changes from @kpreid in f842a67e actually made this even more clear, I think.

I'll leave this issue for a bit longer to give folks the opportunity to comment or suggest improvements, but in lieu of that I'm considering this a "won't fix".

**Comment by bhilburn** [comment]
One thing we could do to clarify this is specifically describe how we are using the word `segment` in the document. That might be the best answer.

Any thoughts on the best way to go about doing that?

**Comment by bhilburn** [comment]
Okay, so in [this discussion for gr-sigmf](https://github.com/ctriant/gr-sigmf/issues/2#issue-230393786), @ctriant is using the word `segment` differently than I'm using it above. He's using it to refer to the entire object (`global`, `capture`, annotation`), rather than the objects within them.

I definitely think this should be clarified in the document. Will spin on how best to do this, and please comment if you have ideas!

**Comment by ctriant** [comment]
@bhilburn In fact, that might be just a mistake of mine. Quoting from [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf): 

> An object structure is represented as a pair of curly bracket tokens surrounding zero or more name/value pairs. 

and

> An  array  structure  is  a  pair  of  square  bracket  tokens  surrounding  zero  or  more values.  The values are separated by commas.

So, as long as the term _segment_ is not used in  [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf), we could use the term _object_ for `global` and every distinct entity contained inside `capture` and `annotation` _arrays_.

**Comment by kpreid** [comment]
I advise against using the term _object_ with a specific way in the SigMF specification. I believe it will be confusing, perhaps particularly for developers using languages that are not JavaScript, or if the specification (or extensions) later starts using JSON objects in ways which are not SigMF namespaced thingies (e.g. an extension represents some data with arbitrary key-value pairs).

Off the top of my head, I would suggest the following terminology (changes), not all of which are really necessary but are intending to step widely around possible confusions:

* Refer to the thing whose syntax is `{...}` as a "JSON object", consistently.
* Refer to JSON objects whose keys are namespaced according to the rules set out in the SigMF specification as "namespaced objects" — or in general, use an adjective, not a noun. Reserve nouns for subtypes that have well-defined roles.
* Never use the word "segment" alone. Call capture segments "capture segments", or possibly use some other name.
* Call annotation segments just "annotations". The "segment" word gives us no benefit here, and annotations are different from capture segments because they can overlap.
* Rename the `capture` and `annotation` fields to be _plural_, since their values are _arrays of those things_.

**Comment by bhilburn** [comment]
Okay, I think we now have the "JSON object" thing, clarifying "segments", and renaming the 'capture' and 'annotation' arrays to be plural, done. Closing this one for now, and if anyone else has thoughts for further improvements based on the current state, please feel free to open a bug or file a new PR!
