### ISSUE TITLE
Annotate modulation 

### ISSUE THREAD

**Issue by ctriant** [gnuradio/SigMF#49]
Referring the [Dyspan 2017 Workshop - Battle of the ModRecs](http://dyspan2017.ieee-dyspan.org/workshop/ieee-dyspan-2017-workshop-battle-modrecs), where the core:comment field was used in order for the contestants to report the classified modulation scheme, I was wondering if it is meaningful to consider an explicit field for that case.

Maybe an optional modulation field in the annotation segments. Any thoughts?

**Comment by djanderson** [comment]
At least in our use case, this would either not be known at the time of capture, or not be relevant to the data set (occupancy measurements where the data are detected power). On the flip side, we have many pieces of information that are necessary for us but probably not necessary in the general case, so we've decided to create our own namespace for metadata specific to our collections. 

So I think better than using core:comment, a better approach would be to have created a 'dyspan17' namespace with parameters specific to those captures: dyspan17:modulation, etc.

**Comment by kpreid** [comment]
Another problem with formalizing this is that as far as I know there is no existing single schema for naming modes which is sufficiently well-defined and specific to really have the amount of detail you want to demodulate & decode or otherwise analyze a signal correctly.

(For example, the ITU emission designators are unambiguous but extremely vague.)

**Comment by bhilburn** [comment]
I like @djanderson's suggestion. Especially since SigMF may be used (indeed, we hope it is) for things other than just comms, de-generalizing the spec by adding them to the `core` namespace sends the wrong message, I think.

One of the things we are discussing in #13, @ctriant, is whether or not providing more standard extension namespaces might be a good idea, and some of the discussion in #4 might be good examples of what should go into that. I think this might fall into the same category.
