### ISSUE TITLE
Consider adding spectrograms as part of the spec

### ISSUE THREAD

**Issue by Teque5** [gnuradio/SigMF#62]
I saw your GRCon talk was excited to see the spectrogram in your first slide, but it was then ignored. :(

I capture LOTS of signal files. Stuff in the KHz to 100s of MHz sample rates. Currently I use the GNU Radio metafile sink generally, and try to keep logical filenames. One thing **extra** that I do, is after captures I run a python tool on a whole directory that will sequentially read all the data that I have captured and dump out a .png spectrogram for each signal capture. This is the ultimate way to browse through your captures with any system.

I propose in addition to having a **xyz.bin** and **xyz.meta**, you add an **_xyz.png_** in the spec.

The spectrograms should be a standard size, say 1024x1024 (w/o axes), and be computed in a logical way. For that image size, if the file is exactly 1048576 complex samples, then every bit will be visible on the image. If the file is larger or smaller than that, then an overlap factor should be calculated that strides though the data to keep the image size constant. I have all this math worked out for complex & real files if we are interested in moving forward with this idea.

Also, the spectrograms MUST be use a quality colormap. The only ones to consider are [Viridis/Magma/Inferno/Plasma/Cubehelix](https://bids.github.io/colormap/). Jet needs to die in a fire.

If all data was kept this way then you could build a previewer that displayed spectrograms and metadata side by side, and put annotations on the actual spectrogram with arrows or highlight similar to how soundcloud annotates audio files. _It would be really cool._

**Comment by smunaut** [comment]
-1

I don't see the point of this being part of the core spec or even having this data pre-computed.
As I showed in the quick prototype back at the Feb hackfest, displaying annotation over the spectrogram sure is cool, but it can easily be done in real-time without needing to precompute anything.

**Comment by djanderson** [comment]
In the workflow you mentioned, SigMF lives 1 step before the spectrograms: instead of standardizing your preferred virtualization, it standardizes the on-disk representation of the data needed to produce any manner of useful representations. IOW, it would make your python script more generally applicable to larger data sets.

**Comment by kpreid** [comment]
I like the idea of visual browsing, but I don't think they should be precomputed and delivered with the data. This would take up more disk space, potentially be incorrectly computed or not updated when edited, and if the user wanted a different, consistent, colormap or other parameter (e.g. min/max level) there would be little benefit.

But there's no reason there can't be a tool that generates these preview files (as @Teque5 already wrote) — it could even be distributed with other SigMF tools/libraries. I just don't think they should be included with datasets.

**Comment by Teque5** [comment]
@smunaut There is no way you are showing spectrograms of GB+ size files in real-time. Even for smaller files, the requirements to do things in real-time are 50dB above just having a simple postcomputed png.

@kpreid / @djanderson I agree. My point here was to perhaps spec a standard for an optionally attached spectrogram that was carefully considered. I've seen some real garbage ones, and they are almost always in [JET](https://www.mathworks.com/help/matlab/ref/jet.html). For extremely small captures it's possible that a spectrogram could be larger in filesize, but typically a <1MiB png is much smaller than my capture. If you wanted to get fancy you can use good lossy compression like [bpg](https://github.com/mirrorer/libbpg) or settle for a sad jpg.

**Comment by kpreid** [comment]
How would you specify the minimum and maximum levels of the color map, or would the creator of the preview have to choose them?

In long files, what about short-duration signals that are omitted from the preview because the stride skipped over them? Could a maximum or average over multiple FFT-frames (lines) be used instead?

**Comment by Teque5** [comment]
@kpreid 

> How would you specify the minimum and maximum levels of the color map, or would the creator of the preview have to choose them?

Well when I do it I chose the global min/max of the spectrogram to be the 'hottest' and 'coolest' points, since an absolute reference across platforms seems like a hard problem. **However**, If we instead stored the final spectrogram as a floating point *matrix*, then a user could specify thier own max/min/colormap. I like this idea, but the only downside is that a preview image would not be available in a file browser. Perhaps the matrix used to create the spectrogram could be also stored in the image metadata. 

>In long files, what about short-duration signals that are omitted from the preview because the stride skipped over them? Could a maximum or average over multiple FFT-frames (lines) be used instead?

I've computed spectrograms both by skipping data and by doing the averaging to capture small events like you describe. While I dislike striding over potentially valuable data, the required extra computation can sometimes be extreme, and the resultant single pixel difference on the output spectrogram is not always worth it. If we decide to move forward I can produce a script or share something that does it both ways, and we can pick in the future.

**Comment by bhilburn** [comment]
Thanks for the suggestion, @Teque5! I really appreciate you taking the time to write it up for discussion `=)` FWIW, I actually heard this request a couple of times at GRCon.

For the same reasons @smunaut, @djanderson, and @kpreid shared earlier on, I don't think this belongs in the `core` namespace (thus making support for it a requirement for `compliant` applications).

BUT, as you and @kpreid pointed out more recently in the conversation, visual browsing would obviously be useful. Indeed, one of the goals for SigMF is to provide some sort of basic static visualization tool. I think the big question, then, is what makes the most sense: a static visualization tool, PSDs, or both?

The advantage of the SV tool is that we aren't shipping around images - just a tool that then does the computation locally, as needed. I suppose the advantage to shipping PSDs is that someone could "browse" through a recording using OS-built in software like a filebrowser. It's not clear to me, though, how it would then map the PSDs to parts of the SigMF recording without needing a SigMF-provided tool? If that's the case, why ship them pre-computed?

Thoughts on this? Am I missing your objective? I admit I might not fully understand the usecase.

**Comment by mbr0wn** [comment]
Maybe we want a generic way of including pictures in the SigMF archive? SigMF file authors might want to include a photo of the receiver setup, or other things we probably haven't thought of yet.

I understand @Teque5 's suggestion, and there are precedents. CoolEdit (this was a pretty nice audio editor back in the day, not open source though) had a thing called 'peak files' which would help displaying long audio captures, because our good old Pentiums at 100 MHz would take a while to process the waveform display otherwise. If the peak file was not present, it would simply take longer to load.

But like @smunaut and the rest, I'm definitely not a fan of making this part of the core standard. Also, who says that a spectrogram is the best way to preview a signal?

**Comment by bhilburn** [comment]
Interesting idea, @mbr0wn! I'll note that attaching other filetypes to the metadata is something that HDF5 supports, and I heard from a few people at GRCon that they do occasionally make use of it. It sounds like everyone is in agreement that making it part of the core standard is off-the-table, so let's chat about whether or not we would want it as part of an extension namespace or something similar.

So, let's assume that we *do* want this. I think the next question is, "how generic do we want this to be?" Would it be limited to pictures? I'm trying to envision what this might look like.

**Comment by bhilburn** [comment]
Okay, I think the consensus, here, is that putting this into the `core` spec is not the right path, but that there is for sure value in being able to distribute this kind of data in SigMF archives. I think this discussion is now about how do we allow for this in an extension namespace, if that's something we want to do. I'll carry it over in #88.

**Comment by cg-sat** [comment]
We had the same idea, to transport spectrogram data via SigMF, because the core spec already contains most of the metadata that is also necessary for a spectrogram. We found a solution that I want to share here:

With #138 a new global parameter `core:num_channels` was added, initially to support stereo audio. But the `core:num_channels` can contain numbers up to 9223372036854775807 and by setting this parameter to the number of frequency bins in your spectrum, you can store your two-dimensional spectrogram data in the dataset. When you look at one frequency bin of the spectrogram over time, then the samples of that specific bin form a time-series-dataset again. In other words, every frequency bin can be seen as a channel in your dataset.

To transport metadata like start/end time and start/end frequency you can use the existing `annotations` and `captures` lists like follows:
```
{ "global": 
  { "core:datatype": "ri16_be",
    "core:version":"1.2.5",
    "core:num_channels": 1000,
    "core:sample_rate": 100 },
  "annotations":
    [ { "core:sample_start": 0,
        "core:freq_lower_edge": 88000000,
        "core:freq_upper_edge": 108000000,
        "core:sample_count": 500 } ],
  "captures":
    [ { "core:sample_start": 0,
        "core:date_time": "2025-07-01T10:00:00.000Z" } ]
}
```
With this metadata you know, that your spectrogram goes from 88MHz until 108MHz with a frequency bin size of 20MHz divided by 1000 channels = 20kHz on the x axis, and on the y axis it starts today 10 o'clock UTC and lasts for 500 samples divided by the sample_rate of 100 = 5 seconds. The amplitude values of the spectrogram are real 16bit signed-integers in big-endian order.

**Comment by Teque5** [comment]
@cg-sat has a pretty clever idea here. I think we should add some unit test to `sigmf-python` for this stretched implementation.
