### ISSUE TITLE
Fields for the Captures

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#74]
So, right now, the only two fields we have in the `Captures` array are `frequency` and `datetime`. There are many other parameters of signal captures, and I'd like to start hammering out what else belongs in the `core` namespace for `Captures` segments.

Other things that are typically parameters of receiver systems:

* Antenna Selection
* Applied Gain
* Applied Corrections (quadrature, DC, flattening, etc.,)
* Pre-selection and baseband filtering
* Decimation Rate / ratio
* Integer or Fractional VCO tuning

So, two questions:

1. Do any of the above make sense in the `Captures` segment, and if so, should they be in `core` or a canonical extension namespace?
    * Let's hold off on discussing how each one is represented, as that could be a long discussion for each one. Let's focus on whether they belong, first, and if the answer is `yes`, we'll have separate discussions about how to describe them.
2. Can you think of any that are missing?

**Comment by kpreid** [comment]
Several of these parameters could change frequently over time (for example, gain if the receiver is using AGC and recording the automatic gain level); hopefully that's being addressed in the general varying-metadata question.

Decimation seems most relevantly expressed as a particular case of filtering — in general the signal may pass through several analog or digital filter stages before the final result. Information about the exact structure of those stages may or may not be available.

I wonder if it makes sense to organize this kind of metadata as a "block diagram of the receiver", i.e. a single list in order of processing stages applied to the signal, some of which have parameters particular to that stage.

Example: Partial description of "RTL-SDR with an upconverter in front" (which I may have wrong):

    [
        {'type': 'antenna', 'gain': ...},
        {'type': 'analog_filter', ...},
        {'type': 'analog_mixer', ...},
        {'type': 'analog_filter', ...},
        {'type': 'analog_filter', ...},
        {'type': 'analog_quadrature_mixer', ...},
        {'type': 'analog_filter', ...},
        {'type': 'analog_agc', ...},
        {'type': 'adc', ...},
        {'type': 'digital_filter', ...},
        {'type': 'digital_quadrature_mixer', ...}
        ...
    ]

* Caveat: Because of the complexity, people might be more likely to get it wrong by copying-without-understanding examples.
* There needs to be the possibility of stages of "unknown/unspecified (gain | filtering | other | all-of-the-above)". It's still useful in the same way that uncalibrated power levels are useful.
* Could handle describing **recordings of demodulated signals** like "this is a (pre|post)-deemphasis recording of the output of a FM detector", which example would be helpful for folks working on e.g. APRS decoding, or other FM/FSK-digital modes as are common in various VHF radio applications.
* Doesn't handle cases where multiple signals are combined in heterogenous ways, but then, neither would likely alternatives.

**Comment by mbr0wn** [comment]
I vote for canonical namespace. @bhilburn, counter-suggestion: How about we start identifying potential namespaces first? Like with the modulation, we will never get it all right. Gain, alone, has multiple ways of expressing it. Some USRPs + DBoard combinations have 3 or 4 gains, or a total gain.

So, we could have one called 'receiver' which is all the receiver settings. As a process suggestion, we could then suggest actual fields for that namespace, which we individually accept into the standard one by one.

**Comment by bhilburn** [comment]
Thanks for sharing your thoughts, @kpreid and @mbr0wn!

I think @kpreid's idea of essentially describing a block diagram of the receiver is interesting. My concern, which he calls out, is creating something overly complex. If we can implement something like that in a way that allows you to describe simple things simple, but also supports more complex metadata for those that want it, I think we'll be in a good place.

@mbr0wn - Good idea regarding laying out what extension namespaces we want, and then going from there. Looking at the original list I posted, and taking @kpreid's feedback into account, I think that condenses into:

  * Antenna
  * Gain (should this be both analog amps and digital?)
  * Digital Signal Processing (applied filters [incl. decim & interp], corrections, etc.,)
  * Converters (ADCs, DACs, and their settings [Integer vs Fractional, etc.,])

I'm struggling the things like pre-selection and baseband filters, which are analog. "Analog Signal Processing" doesn't seem quite right. "Analog Transforms"? Should we also use "Digital Transfroms"? Thoughts on this and the above?

And what else should we add?

**Comment by kpreid** [comment]
> I'm struggling the things like pre-selection and baseband filters, which are analog. "Analog Signal Processing" doesn't seem quite right. "Analog Transforms"? Should we also use "Digital Transfroms"? Thoughts on this and the above?

The kind of uncertainty here is exactly why I suggested an arbitrary block diagram: as details are _needed_ they can be added. Simple cases can be handled by having monolithic standard blocks (e.g. "DirectConversionIQReceiver" or something like that) which can be the sole entry in the block diagram, and if we figure out that the definition of that monolithic block is wrong we can define a new one that supersedes it.

**Comment by bhilburn** [comment]
@kpreid - I think I understand your goal, but I'm struggling to envision what it would look like "on-paper".

Let's take the `DirectConversionIQReceiver` example. How are you imagining that might be described? I think seeing some examples will help me get a clearer picture.

**Comment by kpreid** [comment]
Sorry, I have been unable to get around to writing up the idea in more detail.

**Comment by bhilburn** [comment]
I'm going to close this out for now. It's clear from the discussion that the consensus is that this kind of thing belongs in a canonical extension namespace if we are going to do it. Once we get to the point that someone is willing to take a crack at that, we can take it from there.
