### ISSUE TITLE
Potentially adding a way to note discontinuities in time to the core namespace for capture segments

### ISSUE THREAD

**Issue by pwicks86** [gnuradio/SigMF#89]
One issue I've run across while building out a set of blocks for SigMF is that it's common to want to create capture segments to note a discontinuity in time of the incoming stream of samples, but not to have a known clock to reference against. For example, if a USRP source has an overflow while receiving samples, it will attach a new `rx_time` tag to the next valid sample to notify downstream users of the discontinuity in data and I'd like my SigMF sink block to be able to handle this. It seems like the `core:datetime` is the place to store this data, but in practice this is difficult to actually achieve, since there isn't a good way to know what the timebase is of the `uhd::time_spec_t` in the `rx_time` tag, it could be unix time or it could be time since the USRP was turned on or some other timebase. Certainly we can handle this via an extension, but it seems like this is a common enough occurrence to warrant inclusion in the core namespace. Off the top of my head, we could add something like this to the core namespace for capture segments:

| name  | required | type | description |
| ------------- | ------------- | ------------- | ------------- |
| core:offset_seconds  | false  | uint64 | The whole seconds part of the offset from the beginning of the recording
| core:offset_frac_seconds  | false | uint64 | The fractional part of the offset from the beginning of the recording

**Comment by bhilburn** [comment]
You raise good points! We had some pretty detailed discussions about time offsets early on, including in this issue, #10, which I recommend reading to get some additional background.

So, as I read your write-up, there are two major aspects, here:

1. Including a time offset field(s) in the `core` namespace: So, fundamentally, I don't think I understand why this is useful - it would be great if you could explain it a bit more for me. My confusion comes down to this point, which I'm copying / pasting over from #10:

> Let's say you have "timestamped" data in the metadata, are visualizing the dataset in a reader application, and want to show the timestamped data. Wouldn't the reader app need to convert the timestamp to a sample index in order to map it in the visualization? If that's the case, why not record it with a sample index? Perhaps this is just a question of where do we put the burden - on the writer or reader. Am I misunderstanding something?

It seems to me that in any case you are using those offset numbers, you are also mapping a time to a sample index, in which case you could just use the sample index and sample rate which is already provided - thus, the offset information is redundant. I'm interested in your take, here.

2. The fact that `core:datetime` is not always useful because you don't know what the time actually is: This is an interesting point. And you're right, you don't always know what the `timebase` is (as you called it) of the time tag. If you don't know what the basetime from the receiver is, though, it seems like it doesn't matter, anyway (hence why `core:datetime` is an optional field). If the field exists, then great, a reader can use it. If not, then the reader might as well just use `0.0` as a base, and if it is displaying time information, simply display the time offset derived by sample index.

I'm really interested in your thoughts on the above, @pwicks86!

**Comment by storborg** [comment]
I don't think the current capture segment schema is quite sufficient for a recording which has an inaccurate/nonexistent absolute timebase, but an accurate relative timebase.

Here's an example:

Say you are using a single board computer to record from a B200. Maybe you don't trust the SBC's clock, or maybe it doesn't have an RTC battery in it, so you can't use ``core:datetime``. You write the UHD stream straight to a file, but occasionally, buffer overruns cause a discontinuity in the sample stream. Your capture segments are each tagged with a high-accuracy relative timebase (starting from ``0.0`` or whatever you want) and you can compute the time that has elapsed since the start of the whole recording, but there isn't currently an appropriate field to store it in.

A reason this is a bit of an impedance mismatch from the typical UHD / GR world is that ``uhd.time_spec_t`` et al can be used as both a relative and an absolute (epoch) time value, whereas an ISO-8601 value can really only be used as an absolute time.

Another semantic bit to note here is the using the ``core:datetime`` field for a high-resolution relative timebase sends a message that could be misleading: If you're capturing from an X310 at 200MS/s and you want sample-level alignment between discontinuous capture segments, your ISO-8601 string looks like ``YYYY-MM-DDTHH:MM:SS.SSSSSSSSSZ``. That many digits of fractional seconds shouts "my clock is super accurate!" even when it might not be.

**Comment by pwicks86** [comment]
Don't have much to add apart from what storborg already mentioned in his reply.

**Comment by bhilburn** [comment]
@storborg - Ah, thanks, that comment (from almost six months ago) is really insightful! Okay, yes, I now have a better understanding of this and what @pwicks86 was describing in the original issue. I see, now, how using `datetime` at the capture segment level and not providing any other mechanism is somewhat limiting.

Thinking about it, I think adding the two new fields you recommend, @pwicks86, to `capture` while also keeping `datetime`, though, is really confusing. Why have two different ways to describe time for the same segment?

My knee-jerk thought after reading this was contemplating moving `datetime` to `global` and have each capture segment provide the offsets from that global time. But, I think that's a poor idea, as it completely breaks the separation we have between `global` and `capture`, and means that `capture` can't be understood without information from `global`, which is a deviation from how the spec is designed.

Not super sure how to fix this, which I agree is an issue. I'm interested in further thoughts, here, if anyone has opinions.

**Comment by bhilburn** [comment]
Need to address this for v0.0.2

**Comment by n-west** [comment]
The easy (TM) thing is certainly to punt and say you've started a different recording at that point. Is there a reason other than overflows while writing to disk that something might be desirable? The quick fix for the overflow case seems to be to fill in zeros where samples were missing and you're back to a perfectly good recording and can describe the number of missing samples in an annotation, or have 3 capture segments (one for good data, one for zeros, one for good data)

**Comment by dkozel** [comment]
How do burst receptions fit in with this? I just put together a flowgraph to record 1 second on, 1 second off for a long duration. It's all one logical dataset but I could imagine it being a set of separate recordings or one recording with time metadata identifying the burst edges.

**Comment by n-west** [comment]
I guess under my proposal you choose which of the following makes sense for what you're actually trying to accomplish:

1) Record for the duration you actually want samples for, then annotate the bursts you care about
2) Record the bursts you want and zero-fill the empty spots
3) Each burst recording is a new SigMF Record

If you are doing timed packet reception I would think you want to record the entire duration and the application that reads and processes data is itself is responsible for skipping data it doesn't care about rather than the recording tools.

**Comment by bhilburn** [comment]
So, since this issue was first created, we since added the `global_index` field to the spec, which sits in Captures. I actually think this actually solves the original problem, as it is a way to correlate global sample counts against time and relative reading.

https://github.com/gnuradio/SigMF/blob/master/sigmf-spec.md#the-global_index-pair

@n-west - Let me know if you agree with 👆👆

**Comment by bhilburn** [comment]
Correct. Will leave this open for a bit longer to invite dissenting opinion, but anticipate closing this one out.

**Comment by jacobagilbert** [comment]
@bhilburn I agree than the `global_index` effectively resolves this.

**Comment by jacobagilbert** [comment]
Its been 3 weeks, Im going to close this to push forward on v1.0 release, but please feel free to re-open @pwicks86 if you disagree.
