### ISSUE TITLE
How to  use signal meta data

### ISSUE THREAD

**Issue by dzakwanfalih** [gnuradio/SigMF#91]
i have signal meta data file, how to i'm using this source

**Comment by bhilburn** [comment]
@dzakwanfalih - Sorry for the long delay in getting back to you. That said, I am very confused about your question. So, you have a SigMF file - are you asking how to use it? You need to parse it according to the spec (there are not currently any public SigMF parsing libraries).

I'm going to close this issue for now due to a lack of clarity, but if you have a more specific question, please feel free to re-open it!
