### ISSUE TITLE
Is it allowed to have multiple annotation segments with the same sample_start and sample_count?

### ISSUE THREAD

**Issue by pwicks86** [gnuradio/SigMF#95]
If I have two annotation segments with a `sample_start` and `sample_count` that are equal, is that allowed by the spec? Or should they be merged into a single annotation segment? It seems that there might be situations where it would be desirable to have the the former, for example if I had two automated tools that both added an annotation to the same `sample_start`/`sample_count` pair and wanted to set the `core:generator` tag, then they would by necessity clobber each other.

**Comment by bhilburn** [comment]
Yes, the goal is definitely to allow that for exactly the reason you describe. If, for example, I'm testing two different signal detectors on the same dataset, it's valuable to be able to have all of the annotations from both detectors in the same recording, even if they are identical.

I don't think they should clobber each other in a compliant reader application, though. Is there something in the spec that you think might cause this? If so, I would actually consider that a bug!

**Comment by storborg** [comment]
The problem that I'm guessing @pwicks86 is referring to involves directly mapping annotations to GNU Radio stream tags. If a stream tag corresponds 1:1 with an annotation, then two stream tags with the same start/count (where ``sample_count`` would probably described by a ``packet_len`` tag or something) don't have sufficient information by themselves to determine how the annotation segments were formed (in the case of the SigMF Source) or should be formed (in the case of the SigMF Sink).

As a rough suggestion, I think the easiest way to resolve this impedance mismatch is simply by mapping a stream tag to a whole annotation segment, rather than an individual annotation. This behavior could be sidestepped by certain "special" tags like ``rx_freq``.

Congrats on the baby!

**Comment by pwicks86** [comment]
Yeah, the issue here is figuring exactly how to map annotations to and from stream tags. And yeah, I think that @storborg's solution of making each annotation segment a single tag that encompasses the whole segment is probably a decent way forward. Apart from that, is it worth spelling out in the spec that this is explicitly allowed?

**Comment by bhilburn** [comment]
Great point, @storborg, thanks for the clarification. Thanks for the suggestion, @pwicks86! I made a clarification and pushed it to `master`.
